[#ftl]
[@b.head/]
[@b.toolbar title="新建专业方向"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!save" theme="list"]
    [@b.textfield name="teacher.code" label="代码" value="${teacher.code!}" required="true" maxlength="20"/]
    [@b.textfield name="teacher.name" label="名称" value="${teacher.name!}" required="true" maxlength="20"/]
    [@b.textfield name="teacher.engName" label="英文名" value="${teacher.engName!}" maxlength="100"/]
    [@b.startend label="生效失效日期" 
      name="teacher.beginOn,teacher.endOn" required="false,false" 
      start=teacher.beginOn end=teacher.endOn format="date"/]
    [@b.textfield name="teacher.remark" label="备注" value="${teacher.remark!}" maxlength="30"/]
    [@b.select name="teacher.major.id" label="专业" value="${(teacher.major.id)!}" required="true" 
               style="width:200px;" items=majors option="id,name" empty="..."/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]