[#ftl]
[@b.head/]
[@b.toolbar title="修改专业方向"]bar.addBack();[/@]
[@b.tabs]
  [@b.tab label="基本信息"]
  [@b.form action="!update?id=${stdPerson.id}" theme="list"]
    [@b.textfield name="stdPerson.code" label="代码" value="${stdPerson.code!}" required="true" maxlength="20"/]
    [@b.textfield name="stdPerson.name" label="名称" value="${stdPerson.name!}" required="true" maxlength="20"/]
    [@b.textfield name="stdPerson.engName" label="英文名" value="${stdPerson.engName!}" maxlength="100"/]
    [@b.startend label="生效失效日期" 
      name="stdPerson.beginOn,stdPerson.endOn" required="false,false" 
      start=stdPerson.beginOn end=stdPerson.endOn format="date"/]
    [@b.textfield name="stdPerson.remark" label="备注" value="${stdPerson.remark!}" maxlength="30"/]
    [@b.select name="stdPerson.major.id" label="专业" value="${(stdPerson.major.id)!}" required="true" 
               style="width:200px;" items=majors option="id,name" empty="..."/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
  [/@]
  [#if stdPerson.id??]
  [@b.tab label="建设过程"]
  [@b.div href="stdPerson-journal!search?stdPersonJournal.stdPerson.id=${stdPerson.id}"/]
    [/@]
  [/#if]
[/@]
[@b.foot/]