[#ftl]
[@b.head/]
[@b.toolbar title="新建教师日志信息"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!save" theme="list"]
    [@b.textfield name="teacherJournal.code" label="代码" value="${teacherJournal.code!}" required="true" maxlength="20"/]
    [@b.textfield name="teacherJournal.name" label="名称" value="${teacherJournal.name!}" required="true" maxlength="20"/]
    [@b.textfield name="teacherJournal.engName" label="英文名" value="${teacherJournal.engName!}" maxlength="100"/]
    [@b.startend label="生效失效日期" 
      name="teacherJournal.beginOn,teacherJournal.endOn" required="false,false" 
      start=teacherJournal.beginOn end=teacherJournal.endOn format="date"/]
    [@b.textfield name="teacherJournal.remark" label="备注" value="${teacherJournal.remark!}" maxlength="30"/]
    [@b.select name="teacherJournal.major.id" label="专业" value="${(teacherJournal.major.id)!}" required="true" 
               style="width:200px;" items=majors option="id,name" empty="..."/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]